//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosqueapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MosqueLink
    {
        public int MosqueLinkid { get; set; }
        public Nullable<int> Hadithid { get; set; }
        public Nullable<int> Mosqueid { get; set; }
    
        public virtual Hadith Hadith { get; set; }
        public virtual Masjid Masjid { get; set; }
    }
}
