//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosqueapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mosqueappEntities : DbContext
    {
        public mosqueappEntities()
            : base("name=mosqueappEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Hadith> Hadiths { get; set; }
        public virtual DbSet<Loginuser> Loginusers { get; set; }
        public virtual DbSet<MosqueLink> MosqueLinks { get; set; }
        public virtual DbSet<Prayertime> Prayertimes { get; set; }
        public virtual DbSet<Countrydata> Countrydatas { get; set; }
        public virtual DbSet<Worldcity> Worldcities { get; set; }
        public virtual DbSet<LanguageInput> LanguageInputs { get; set; }
        public virtual DbSet<Masjid> Masjids { get; set; }
    }
}
