//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosqueapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prayertime
    {
        public int Prayertimeid { get; set; }
        public string Fajr { get; set; }
        public string Fajrnamaaz { get; set; }
        public string Fajrazaan { get; set; }
        public string Shuruq { get; set; }
        public string Dhuhr { get; set; }
        public string Dhuhrazaan { get; set; }
        public string Dhuhrnamaaz { get; set; }
        public string Asr { get; set; }
        public string Asrazaan { get; set; }
        public string Asrnamaaz { get; set; }
        public string Maghrib { get; set; }
        public string Maghribazaan { get; set; }
        public string Maghribnamaaz { get; set; }
        public string Isha { get; set; }
        public string Ishaazaan { get; set; }
        public string Ishanamaaz { get; set; }
        public string AlJumuanamaaz { get; set; }
        public string AlJumuaazaan { get; set; }
    }
}
