//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mosqueapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worldcity
    {
        public int Worldcitylistid { get; set; }
        public string City { get; set; }
        public string City_ascii { get; set; }
        public Nullable<decimal> Latitute { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public string Countryname { get; set; }
        public string Countrycode { get; set; }
        public string countryiso { get; set; }
    }
}
